Repository Dulce-Work-Schedule/2018.1-Dulce_Sector, pull requests merged in 2018-06, with the labels that each got.

#13 12 deploy continuo
  .travis.yml
  Docker/Test/env/.keep
  Environments/Development/Client/Dockerfile
  Environments/Development/Server/Dockerfile
  Environments/Development/Variables/mongo.env
  Environments/Development/Variables/rabbitmq.env
  Environments/Development/build.yml
  Environments/Development/start-deps.yml
  Environments/Development/start-sector.yml
  Environments/Production/Client/Dockerfile
  Environments/Production/Server/Dockerfile
  Environments/Production/build.yml
  Environments/Test/Client/Dockerfile
  Environments/Test/Server/Dockerfile
  Environments/Test/Variables/mongo.env
  Environments/Test/Variables/rabbitmq.env
  Environments/Test/build.yml
  Environments/Test/env/.keep
  Environments/Test/start-sector.yml
  utils/deploy.sh
  utils/script_coveralls.sh
Labels: 0-Devops, 1-Viabilidade Técnica, 2-Deploy Contínuo, 4-Débito Técnico, 5-Intermediário

#16 Fix #15 acrescentando validações e campo hospital_id
  Client/api.js
  Server/_sector.js
  Server/package.json
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Adicionado, 5-Intermediário

#19 Fix #17, Fix #18 Fazendo rotas de listByHospital e listByID
  Client/api.js
  Server/_sector.js
Labels: 0-Developers, 1-Produto, 2-Feature, 3-Task, 4-Adicionado, 5-Iniciante
